### ISSUE TITLE
Tests need to be updated to support Spree 2.4

### ISSUE THREAD

**Issue by bryanmtl** [DynamoMTL/spree_subscriptions#16]

**Comment by 0903** [comment]
-- Please reply above this line --

Hi, there! 

Thanks for sending us a message; I want to let you know that we’ve
received your email, and we’ll get back to you as quickly as we can.


Daniel Markham
Blue Bottle Customer Support

P.S. If you contacted us about an existing order and you emailed us
from an address that’s different than the one linked to your Blue
Bottle Coffee account, please let us know the full name and email
you’d like associated with your support request.


-----------------------------------------------------------
## Dynamomtl/spree_Subscriptions sent a message, on Jun 25 @ 12:38pm (PDT):



	-
 Reply to this email directly or view it on GitHub [1].

Links:
------
[1] https://github.com/DynamoMTL/spree_subscriptions/issues/16


-----------------------------------------------------------

**Comment by bryanmtl** [comment]
Some basic steps here: 

https://github.com/DynamoMTL/spree_subscriptions/tree/feature/update-specs

**Comment by 0903** [comment]
-- Please reply above this line --

Hi, there! 

Thanks for sending us a message; I want to let you know that we’ve
received your email, and we’ll get back to you as quickly as we can.


Daniel Markham
Blue Bottle Customer Support

P.S. If you contacted us about an existing order and you emailed us
from an address that’s different than the one linked to your Blue
Bottle Coffee account, please let us know the full name and email
you’d like associated with your support request.


-----------------------------------------------------------
## Dynamomtl/spree_Subscriptions sent a message, on Jun 25 @ 12:39pm (PDT):



	Some basic steps here: 

	https://github.com/DynamoMTL/spree_subscriptions/tree/feature/update-specs
[1] 

	-
 Reply to this email directly or view it on GitHub [2].

Links:
------
[1]
https://github.com/DynamoMTL/spree_subscriptions/tree/feature/update-specs
[2]
https://github.com/DynamoMTL/spree_subscriptions/issues/16#issuecomment-115372737


-----------------------------------------------------------
