### ISSUE TITLE
[solidus] fix failing api spec 

### ISSUE THREAD

**Issue by peterberkenbosch** [DynamoMTL/spree_subscriptions#24]
```
./spec/controllers/spree/api/subscriptions_controller_spec.rb:20 # Spree::Api::SubscriptionsController restricts access to subscriptions
```

**Comment by DanielWright** [comment]
Rather than tagging `solidus`, does it make sense to make a fork?

**Comment by bryanmtl** [comment]
I think that makes sense. We can fork to Glossier and perhaps rename the extension `solidus_subscriptions`

**Comment by peterberkenbosch** [comment]
yup, sounds good to me.

**Comment by bryanmtl** [comment]
@peterberkenbosch Is that something you can do?

**Comment by peterberkenbosch** [comment]
@bryanmtl done: https://github.com/glossier/solidus_subscriptions, working on getting master on solidus and rename the gem

**Comment by bryanmtl** [comment]
:boom: Thank you.

**Comment by peterberkenbosch** [comment]
https://github.com/glossier/solidus_subscriptions/issues/1
