### ISSUE TITLE
Similar extension

### ISSUE THREAD

**Issue by onedanshow** [DynamoMTL/spree_subscriptions#6]
Learned about Dynamo during SpreeConf last week.  I see you guys have a similar extension for subscriptions. Feel free to get ideas from my code, and/or contribute back:

https://github.com/onedanshow/spree-subscribe

**Comment by 0903** [comment]
-- Please reply above this line --

Hi, there! 

Thanks for sending us a message; I want to let you know that we’ve
received your email, and we’ll get back to you as quickly as we can.


Daniel Markham
Blue Bottle Customer Support

P.S. If you contacted us about an existing order and you emailed us
from an address that’s different than the one linked to your Blue
Bottle Coffee account, please let us know the full name and email
you’d like associated with your support request.


-----------------------------------------------------------
## Dynamomtl/spree_Subscriptions sent a message, on Jun 25 @ 12:38pm (PDT):



	Closed #6 [1]. 

	-
 Reply to this email directly or view it on GitHub [2].

Links:
------
[1] https://github.com/DynamoMTL/spree_subscriptions/issues/6
[2]
https://github.com/DynamoMTL/spree_subscriptions/issues/6#event-340426179


-----------------------------------------------------------
