### ISSUE TITLE
Subscriptions section of account page kinda sucks

### ISSUE THREAD

**Issue by DanielWright** [DynamoMTL/spree_subscriptions#7]
- [ ] Not especially user-friendly date-format in the Next Shipment column
- [ ] No frequency/quantity information in the Products column
- [ ] No mechanisms to pause/cancel a subscription

**Comment by 0903** [comment]
-- Please reply above this line --

Hi, there! 

Thanks for sending us a message; I want to let you know that we’ve
received your email, and we’ll get back to you as quickly as we can.


Daniel Markham
Blue Bottle Customer Support

P.S. If you contacted us about an existing order and you emailed us
from an address that’s different than the one linked to your Blue
Bottle Coffee account, please let us know the full name and email
you’d like associated with your support request.


-----------------------------------------------------------
## Dynamomtl/spree_Subscriptions sent a message, on Jun 25 @ 12:38pm (PDT):



	Closed #7 [1]. 

	-
 Reply to this email directly or view it on GitHub [2].

Links:
------
[1] https://github.com/DynamoMTL/spree_subscriptions/issues/7
[2]
https://github.com/DynamoMTL/spree_subscriptions/issues/7#event-340426182


-----------------------------------------------------------
